sonar.projectKey=nadhmi54_AlphaRoom-backend
sonar.organization=nadhmi54
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
